# Generated by Django 5.1.6 on 2025-03-12 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "permissions": [
                    ("can_edit_event", "Can edit the event"),
                    ("can_delete_event", "Can delete the event"),
                    ("can_manage_speakers", "Can manage speakers"),
                    ("can_view_event", "Can view event details"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                blank=True, related_name="organized_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
