# Generated by Django 5.1.6 on 2025-03-12 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_event_options_alter_event_organizers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={},
        ),
    ]
