# Generated by Django 5.1.6 on 2025-03-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="virtual_location",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
