# Generated by Django 5.1.6 on 2025-03-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_event_virtual_location_alter_event_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("in_person", "In-Person"),
                    ("virtual", "Virtual"),
                    ("hybrid", "Hybrid"),
                ],
                default="in_person",
                max_length=10,
            ),
        ),
    ]
